name: Documentation links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 1'

permissions:
  contents: read

jobs:
  lychee:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --mode markdown --no-progress --exclude localhost --exclude 127.0.0.1 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
